#!/usr/bin/env python3
"""Generate soft, sparse eat-SFX PCM into src/sfx_data.h (synthetic, no third-party assets)."""

from __future__ import annotations

import math
import os

SAMPLE_RATE = 16000
OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "src", "sfx_data.h")
# Keep overall level modest — desk-toy quiet, not arcade
PEAK = 9000


def clamp16(x: float) -> int:
    return max(-32767, min(32767, int(x)))


def make_soft_blip(
    duration_ms: float,
    f0: float,
    f1: float | None = None,
    harmonics: float = 0.12,
) -> list[int]:
    """Soft sine blip with gentle attack/decay (no noise clicks)."""
    n = int(SAMPLE_RATE * duration_ms / 1000.0)
    samples: list[int] = []
    attack = max(1, int(0.012 * SAMPLE_RATE))
    release = max(1, int(0.035 * SAMPLE_RATE))
    for i in range(n):
        t = i / SAMPLE_RATE
        frac = i / max(1, n - 1)
        hz = f0 if f1 is None else f0 + (f1 - f0) * frac
        env = 1.0
        if i < attack:
            env = i / attack
        elif i > n - release:
            env = (n - i) / release
        # raised-cosine body so it isn't a harsh gate
        env *= 0.5 - 0.5 * math.cos(math.pi * min(1.0, frac * 2.0 if frac < 0.5 else 2.0 * (1.0 - frac)))
        tone = math.sin(2 * math.pi * hz * t)
        tone += harmonics * math.sin(2 * math.pi * hz * 2.0 * t)
        samples.append(clamp16(tone * env * PEAK))
    return samples


CLIPS = [
    # plant: soft high tick
    ("sfx_eat_plant", make_soft_blip(45, 520, 680, harmonics=0.08)),
    # herb eaten (reserved; used on kill if re-enabled)
    ("sfx_eat_herb", make_soft_blip(70, 280, 220, harmonics=0.1)),
    # carn eaten
    ("sfx_eat_carn", make_soft_blip(90, 180, 140, harmonics=0.1)),
    # garbage: muted mid thup
    ("sfx_eat_garbage", make_soft_blip(55, 240, 200, harmonics=0.05)),
    # spore: quiet airy rise
    ("sfx_eat_spore", make_soft_blip(65, 400, 560, harmonics=0.06)),
]


def emit_array(name: str, samples: list[int]) -> str:
    lines = [f"static const int16_t {name}[] PROGMEM = {{"]
    row: list[str] = []
    for i, s in enumerate(samples):
        row.append(str(s))
        if len(row) == 12 or i == len(samples) - 1:
            lines.append("  " + ", ".join(row) + (",", "")[i == len(samples) - 1])
            row = []
    lines.append("};")
    lines.append(f"static const size_t {name}_len = {len(samples)};")
    return "\n".join(lines)


def main() -> None:
    parts = [
        "// Auto-generated by tools/gen_sfx.py — do not edit by hand.",
        "// Soft synthetic eat SFX, 16-bit mono @ 16 kHz.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "#include <pgmspace.h>",
        "",
        f"static const int SFX_SAMPLE_RATE = {SAMPLE_RATE};",
        "",
    ]
    for name, samples in CLIPS:
        parts.append(emit_array(name, samples))
        parts.append("")

    out = os.path.normpath(OUT_PATH)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    print(f"Wrote {out} ({sum(len(s) for _, s in CLIPS)} samples total)")


if __name__ == "__main__":
    main()
